name: Build & publish container

on:
  push:
    branches:
      - 'v7.3'
      - 'v7.4'
      - 'v8.0'
      - 'v8.1'

env:
  GIT_REMOTE_URL: ${{ github.server_url }}/${{ github.repository }}.git
  CI_TOOLS_SETUP: https://raw.githubusercontent.com/SGSGermany/ci-tools/main/setup.sh

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    concurrency: build-${{ github.ref }}

    env:
      REGISTRY: ghcr.io
      OWNER: sgsgermany
      IMAGE: php-fpm

    steps:
      - name: Setup CI tools
        run: |
          . <(curl -fsS -L "$CI_TOOLS_SETUP" | bash -s ~/ci-tools)
          echo "CI_TOOLS_PATH=$CI_TOOLS_PATH" | tee -a "$GITHUB_ENV"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into container registry ${{ env.REGISTRY }}
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deduce 'VERSION' environment variable
        run: |
          [[ "$GITHUB_REF" =~ ^refs/heads/v([0-9]+\.[0-9]+)$ ]]
          echo "VERSION=${BASH_REMATCH[1]}" | tee -a "$GITHUB_ENV"

      - name: Generate container image tags
        run: |
          source <(./tags.sh)
          echo "VERSION=$VERSION" | tee -a "$GITHUB_ENV"
          echo "DEFAULT_TAGS=${DEFAULT_TAGS:-v$VERSION-default}" | tee -a "$GITHUB_ENV"
          echo "BASE_TAGS=${BASE_TAGS:-v$VERSION}" | tee -a "$GITHUB_ENV"

      - name: Check for config changes
        run: |
          buildah unshare ./default/check-config.sh

      - name: Build 'default' container image
        run: |
          buildah unshare ./default/build.sh

      - name: Metadata of 'default' container image
        run: |
          "$CI_TOOLS_PATH/containers/get-metadata.sh" "$REGISTRY/$OWNER" "$IMAGE:v$VERSION-default"

      - name: Build 'base' container image
        run: |
          buildah unshare ./base/build.sh

      - name: Metadata of 'base' container image
        run: |
          "$CI_TOOLS_PATH/containers/get-metadata.sh" "$REGISTRY/$OWNER" "$IMAGE:v$VERSION"

      - name: Push 'default' container image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE }}
          registry: ${{ env.REGISTRY }}/${{ env.OWNER }}
          tags: ${{ env.DEFAULT_TAGS }}

      - name: Push 'base' container image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE }}
          registry: ${{ env.REGISTRY }}/${{ env.OWNER }}
          tags: ${{ env.BASE_TAGS }}
